Controllers/PartyController.cs
using CruiseshipApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Migrations;
using System.EnterpriseServices;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace CruiseshipApp.Controllers
{
    public class PartyController : Controller
    {
        CruiseshipDbEntities db = new CruiseshipDbEntities();
        public ViewResult Index()
        {
            return View(db.Party_hall_Table.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Hall Id Required");
            }
            Party_hall party_Hall = db.Party_hall_Table.Find(id);
            if (party_Hall == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Movie Not Found");
            }
            Party_hall party = new Party_hall();

            using (CruiseshipDbEntities db = new CruiseshipDbEntities())
            {
                party = db.Party_hall_Table.Where(x => x.Hall_id == id).FirstOrDefault();
            }
            return View(party_Hall);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Party_hall party_Hall)
        {
            string fileName = Path.GetFileNameWithoutExtension(party_Hall.ImageFile.FileName);
            string extension = Path.GetExtension(party_Hall.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            party_Hall.Image = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            party_Hall.ImageFile.SaveAs(fileName);
            using (CruiseshipDbEntities db = new CruiseshipDbEntities())
            {
                db.Party_hall_Table.Add(party_Hall);
                db.SaveChanges();
                TempData["AlertMessage"] = "Party Hall Added Successfully...!";
            }
            ModelState.Clear();
            return RedirectToAction("/Index");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Hall Id Required");
            }
            Party_hall party_Hall = db.Party_hall_Table.Find(id);
            if (party_Hall == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Hall not Found");
            }
            return View(party_Hall);
        }
        [HttpPost]
        public ActionResult Edit(int id)
        {
            /*Party_hall party = db.Party_hall_Table.Find(id);
            string fileName = Path.GetFileNameWithoutExtension(party.ImageFile?.FileName);
            string extension = Path.GetExtension(party.ImageFile?.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            party.Image = "~/Image/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
            party.ImageFile?.SaveAs(fileName);
            using (CruiseshipDbEntities db = new CruiseshipDbEntities())
            {
                db.Party_hall_Table.AddOrUpdate(party);
                db.SaveChanges();
            }
            ModelState.Clear();
            return View();*/

            Party_hall party_Hall = db.Party_hall_Table.Find(id);
            UpdateModel(party_Hall);
            db.SaveChanges();
            TempData["AlertMessage"] = "Party Hall Updated Successfully...!";
            return RedirectToAction("/Index");

        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Hall Id Required");
            }
            Party_hall party_Hall = db.Party_hall_Table.Find(id);
            if (party_Hall == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound, "Hall not Found");
            }
            return View(party_Hall);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Party_hall party_Hall = db.Party_hall_Table.Find(id);
            db.Party_hall_Table.Remove(party_Hall);
            db.SaveChanges();
            TempData["AlertMessage"] = "Party Hall Deleted Successfully...!";
            return RedirectToAction("/Index");
        }



/*=============================================      VOYAGER BOOKING SECTION      =============================================*/




        public ViewResult PartyHallBooking()
        {
            return View(db.Party_hall_Table.ToList());
        }

        public ActionResult Book(int? id)
        {
            Party_hall party_Hall = db.Party_hall_Table.Find(id);
            Session["iid"] = id;
            return View(party_Hall);
        }
        [HttpPost]
        public ActionResult Confirm(string dt, string tm)
        {
            var iids = Session["iid"];
            CruiseshipDbEntities db = new CruiseshipDbEntities();
            string currentDate1 = DateTime.Now.ToString("MM/dd/yyyy hh mm tt");
            Party_hall party_Hall = db.Party_hall_Table.Find(iids);
            int ssid = Convert.ToInt32(Session["login_id"]);
            var newss = db.Voyagers.Where(x => x.Login_id == ssid).FirstOrDefault();
            var sid = Convert.ToInt32(iids);

            var newss1 = db.Booking_details_Table.Where(x => x.Booking_for_id == sid && x.Date == dt && x.Time == tm).ToList();
            var newss2 = db.Booking_details_Table.Where(x => x.Booking_for_id == sid && x.Voyager_id == newss.Voyager_id && x.Date == dt && x.Time == tm).FirstOrDefault();
            int count1 = newss1.Count;

            if (newss2 != null)
            {
                TempData["AlertMessage"] = "Party Hall is already booked...!";
            }
            else
            {
                if (count1 >= 1)
                {
                    TempData["AlertMessage"] = "Party Hall is not Available. select a different Date...!";
                }
                else
                {
                    Booking_details details = new Booking_details();
                    details.Booking_type = "Party hall";
                    details.Booking_for_id = party_Hall.Hall_id;
                    details.Voyager_id = newss.Voyager_id;
                    details.Date = dt;
                    details.Time = tm;

                    var check1 = db.Logins.Where(y => y.Login_id == ssid && y.Usertype == "Premium").FirstOrDefault();
                    if (check1 != null)
                    {
                        details.Status = "Premium Paid";
                        db.Booking_details_Table.Add(details);
                        db.SaveChanges();
                    }
                    else
                    {
                        details.Status = "Payment Pending";
                        db.Booking_details_Table.Add(details);
                        db.SaveChanges();
                    }

                    Payment payment = new Payment();
                    payment.Booking_details_id = details.Booking_details_id;
                    payment.Booking_for = "Party Hall";
                    payment.Amount = party_Hall.Price;
                    payment.Date = currentDate1;
                    db.Payments.Add(payment);
                    db.SaveChanges();

                    TempData["AlertMessage"] = "Party Hall Booked Successfully...!";
                }
            }
            return RedirectToAction("PartyHallBooking");
        }

        public ActionResult ViewBookings()
        {
            int ssid = Convert.ToInt32(Session["login_id"]);
            var newss = db.Voyagers.Where(x => x.Login_id == ssid).FirstOrDefault();
            using (CruiseshipDbEntities dd = new CruiseshipDbEntities())
            {
                var result = (from bd in dd.Booking_details_Table
                              join pt in dd.Party_hall_Table
                              on bd.Booking_for_id equals pt.Hall_id
                              where bd.Voyager_id == newss.Voyager_id
                              select new PartyBookingDetails
                              {
                                  Booking_details_id = bd.Booking_details_id,
                                  Name = bd.Voyager.First_name + " " + bd.Voyager.Last_name,
                                  Hallname = pt.Hall_name,
                                  Occasion = pt.Occasion,
                                  Date = bd.Date,
                                  Time = bd.Time,
                                  Amount = pt.Price,
                                  Status = bd.Status,
                              }).ToList();
                return View(result);
            }
        }

        public ActionResult PartyPayment(int? id)
        {
            Session["bid"] = id;

            /*int ssid = Convert.ToInt32(Session["login_id"]);
            var newss = db.Voyagers.Where(x => x.Login_id == ssid).FirstOrDefault();

            var check1 = db.Logins.Where(y => y.Login_id == ssid && y.Usertype == "Premium").FirstOrDefault();
            if (check1 != null)
            {
                TempData["AlertMessage"] = "Premium users need not make payment...!";
                return RedirectToAction("ViewBookings");
            }

            var check = db.Payments.Where(y => y.Booking_details_id == id).FirstOrDefault();
            if (check != null)
            {
                *//*return RedirectToAction("ConfirmPayment");*//*
                TempData["AlertMessage"] = "Payment already done...!";
                return RedirectToAction("ViewBookings");

Views/Party/Book.cshtml
@model CruiseshipApp.Models.Party_hall

@{
    ViewBag.Title = "Book";
    Layout = "~/Views/Home/Voyager_LayoutPage.cshtml";
}

<center>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />


    <h1>BOOK PARTY HALL</h1>

    <form method="Post" action="/Party/Confirm">


         
        <dl style="width:400px" class="dl-horizontal">
            <dt>
                Hall Name<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Hall_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Time)<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>

            @*    <dt>
            @Html.DisplayNameFor(model => model.Occasion)<br /><br />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Occasion)
        </dd>*@


            <dt>
                @Html.DisplayNameFor(model => model.Price)<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            <dt>
                Image<br /><br />
            </dt>

            <dd>
                <img src="@Url.Content(Model.Image)" width="300" height="170" /><br /><br>
            </dd>
            
            <dt>
                Date
            </dt>

            <dd>

                <input type="date" name="dt" min="2023-08-20" class="form-control" required><br />
            </dd>

            <dt>
                Time
            </dt>

            <dd>
                <select name="tm" class="form-control" required>
                    <option value="9:00">9:00 AM</option>
                    <option value="16:00">4:00 PM</option>
                    <option value="22:00">10:00 PM</option>
                </select>
            </dd>

        </dl>
        <input type="submit" name="Confirm" value="Confirm" class="btn btn-success" />
        <a href="PartyHallBooking" class="btn btn-danger">Cancel</a>
    </form>
</center>

Views/Party/Create.cshtml
@model CruiseshipApp.Models.Party_hall

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Party/Party_LayoutPage.cshtml";
}

<center>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <h1>ADD PARTY HALL</h1><br />
    <br />


    @using (Html.BeginForm("Create", "Party", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal; fa-text-width;" style="width:500px">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Hall_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hall_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hall_name, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" required />
                </div><br /><br />
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                    <a href="Index?" class="btn btn-default">Cancel </a>
                </div>
            </div>
        </div>
    }

</center> 

Views/Party/Delete.cshtml
@model CruiseshipApp.Models.Party_hall

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Party/Party_LayoutPage.cshtml";
}


<center>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />


    <h1>Are you sure you want to delete this?</h1>
    <hr />

    <div>

        <div>
            <dl class="dl-horizontal" style="width: 400px">
                <dt>
                    Hall
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Hall_name)<br /><br />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Time)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Time)<br /><br />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Occasion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Occasion)<br /><br />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Image)
                </dt>

                <dd>
                    <img src="@Url.Content(Model.Image)" width="200" height="200" /><br /><br />

                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>

                @*<dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>*@

            </dl>
        </div>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a href="Index?" class="btn btn-default">Cancel </a>

            </div>
        }
    </div>
</center>

Views/Party/Details.cshtml
@model CruiseshipApp.Models.Party_hall

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Party/Party_LayoutPage.cshtml";
}

<center>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <h1>DETAILS</h1><br />

    <div>

        <hr />
        <dl class="dl-horizontal" style="width:400px">
            <dt>
                @Html.DisplayNameFor(model => model.Hall_name)<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Hall_name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Time)<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Occasion)<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Occasion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Image)<br /><br />
            </dt>

            <dd>
                <img src="@Url.Content(Model.Image)" width="350" height="250" /><br /><br />
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Price)<br /><br />
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Price)
            </dd>

            @*        <dt>
                    @Html.DisplayNameFor(model => model.Status)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Status)
                </dd>*@

        </dl>
    </div>

</center>

Views/Party/Edit.cshtml
@model CruiseshipApp.Models.Party_hall

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Party/Party_LayoutPage.cshtml";
}

<center>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <h1>EDIT PARTY CENTRE</h1><br />
    <br />

    @using (Html.BeginForm("Edit", "Party", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal; fa-text-width;" style="width:500px">
     
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Hall_id)

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Hall_name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Hall_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Hall_name, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

@*            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" required />
                </div><br /><br />
            </div>*@

            <div class="form-group" style="color:white">
                @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div><br /><br />
            </div>

            @*        <div class="form-group">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

  

Views/Party/Index.cshtml
@model IEnumerable<CruiseshipApp.Models.Party_hall>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Party/Party_LayoutPage.cshtml";
}

<center>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />


    <h1>MANAGE PARTY HALL</h1>


    @if (TempData["AlertMessage"] != null)
    {
        <div class="alert alert-info">
            <strong>@TempData["AlertMessage"]</strong> 
        </div>
    }
</center>
@*        <p>
            @Html.ActionLink("Add Party Hall", "Create")
        </p>*@

    <a href="Create?" class="btn btn-success">ADD NEW PARTY HALL</a><br /><br />

        <table class="table">
            <tr>
                <th>
                    Hall
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Time)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Occasion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                @*<th>
                           @Html.DisplayNameFor(model => model.Status)
                    </th>*@
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hall_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
                    <td>
                        <img src="@Url.Content(item.Image)" width="120" height="80" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Occasion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                        @*</td>
                                    <td>
                                    @Html.DisplayFor(modelItem => item.Status)
                            </td>*@
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.Hall_id })
                        @Html.ActionLink("Details", "Details", new { id = item.Hall_id })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Hall_id })

                        <a href="Edit?id=@item.Hall_id" class="btn btn-info">EDIT</a>
*@

                        <a href="Details?id=@item.Hall_id" class="btn btn-info">DETAILS</a>
                        <a href="Delete?id=@item.Hall_id" class="btn btn-danger">DELETE</a>
                    </td>
                </tr>
            }

        </table>

Views/Party/PartyHallBooking.cshtml
@model IEnumerable<CruiseshipApp.Models.Party_hall>

@{
    ViewBag.Title = "PartyHallBooking";
    Layout = "~/Views/Home/Voyager_LayoutPage.cshtml";
}

<center>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />


    <h1>PARTY HALL BOOKING</h1>
    <br />

    @if (TempData["AlertMessage"] != null)
    {
        <div class="alert alert-info ">
            <strong>@TempData["AlertMessage"]</strong> 
        </div>
    }

</center>

<a href="ViewBookings" class="btn btn-info"> My Bookings</a>
<br />
<br />




<table class="table">
    <tr>
        <th>
            Hall Name
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Occasion)
        </th>
        <th>
            Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        @*  <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Hall_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Occasion)
            </td>
            <td>
                <img src="@Url.Content(item.Image)" width="120" height="80" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            @*   <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>*@
            <td>

                <a href="Book?id=@item.Hall_id" class="btn btn-success"> Book</a>
            </td>
        </tr>
    }

</table>

Views/Party/ViewBookings.cshtml
@model IEnumerable<CruiseshipApp.Models.PartyBookingDetails>

@{
    ViewBag.Title = "ViewBookings";
    Layout = "~/Views/Home/Voyager_LayoutPage.cshtml";
}

<center>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />


    <h1>My Bookings</h1>
    <br />

    @if (TempData["AlertMessage"] != null)
    {
        <div class="alert alert-info ">
            <strong>@TempData["AlertMessage"]</strong> 
        </div>
    }
    <table class="table">
        <tr>
            @*        <th>
                    @Html.DisplayNameFor(model => model.Booking_details_id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Booking_type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Booking_for_id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Voyager_id)
                </th>*@

            @*
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>*@
            <th>
                Hall Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Occasion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>

        </tr>

        @foreach (var item in Model)
        {
            <tr>
                @*        <td>
                        @Html.DisplayFor(modelItem => item.Booking_details_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking_type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Booking_for_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Voyager_id)
                    </td>*@

                @*
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Hallname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Occasion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>



                @if (item.Status == "Payment Pending")
                {
                    <td>
                        <a href="PartyPayment?id=@item.Booking_details_id" class="btn btn-success"> Payment</a>
                    </td>
                }
                else /*if (item.Status == "PremiumPaid")*/
                {

                }
            </tr>
        }

    </table>

    <a href="PartyHallBooking?" class="btn btn-info">Back to List</a>

</center>